spring.application.name=fitnessmembership
server.port=8080

# JSP config
spring.mvc.view.prefix=/WEB-INF/views/
spring.mvc.view.suffix=.jsp

# Disable Thymeleaf
spring.thymeleaf.enabled=false

# Security credentials
spring.security.user.name=admin
spring.security.user.password=admin123